name: Weekly Auto-Update

on:
  schedule:
    # Run every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install requests feedparser beautifulsoup4 arxiv
      
      - name: Update README with latest content
        run: |
          python scripts/update_readme.py
      
      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet README.md || echo "changes=true" >> $GITHUB_OUTPUT
      
      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git commit -m "chore: auto-update README with latest content [skip ci]"
          git push
      
      - name: Create issue if update fails
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Weekly auto-update failed',
              body: 'The weekly auto-update workflow failed. Please check the workflow run for details.',
              labels: ['automation', 'bug']
            });
